In [65]:
from numpy import dot
from numpy.linalg import norm

a = np.matrix([[1, 2], [3, 4], [3, 8]])
b = np.matrix([[2, 3], [3, 8], [1, 7]])

cos_sim = dot(a, a.T)/(norm(a)*norm(a.T))
norm(a)

10.14889156509222

In [101]:
import numpy as np
import pandas as pd
import pickle

movies   = pd.read_csv('./data/movies_w_imgurl.csv');
sim = load_obj('movie-cos-similarity')

def save_obj(obj, name ):
    'Saves object to a local file'
    with open('./obj/'+ name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name ):
    'Loads local object'
    with open('./obj/' + name + '.pkl', 'rb') as f:
        return pickle.load(f)
    


In [103]:
# make id dictionarie to accelerate id access
movieIds = {}
index = 0;
for movie in movies['movieId']:
    movieIds[str(movie)] = index;
    index+=1 #incremrent index

In [348]:
def get_partial_similarity(user_movieIds):
    user_sim = False
    for movie in user_movieIds:
        
        if type(user_sim) == type(False):
            user_sim = sim[movieIds[str(movie)], :]
        else:
            user_sim = np.vstack([user_sim, sim[movieIds[str(movie)], :]])
    
    return user_sim

def get_topN(userId, topN):
    'Returns top N recommendations'
    ratings = pd.read_csv('./data/ratings.csv')
    ratings = ratings[ratings['userId'] == userId]
    
    user_rating = np.matrix(ratings['rating']).T
    user_sim = get_partial_similarity(list(ratings['movieId']))
    print(list(ratings['movieId']))
    recommendation = np.divide(np.matmul(user_sim.T, user_rating), np.add(sim_sum, 1).T)
    recommendation = np.concatenate((recommendation, np.matrix(list(movieIds.keys())).T), axis=1)
    return recommendation
    #return recommendation[recommendation[:,0].argsort()]

r = get_topN(3, 30)

r = r[np.lexsort(r[:,0].T)]
r[:,-20:,:]

[[1.         0.56825577 0.06551191 ... 0.         0.03904665 0.        ]
 [0.56825577 1.         0.         ... 0.         0.         0.        ]
 [0.06551191 0.         1.         ... 0.         0.14621366 0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.29662436]
 [0.03904665 0.         0.14621366 ... 0.         1.         0.71397031]
 [0.         0.         0.         ... 0.29662436 0.71397031 1.        ]]
[[1.         0.56825577 0.06551191 ... 0.         0.03904665 0.        ]
 [0.56825577 1.         0.         ... 0.         0.         0.        ]
 [0.06551191 0.         1.         ... 0.         0.14621366 0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.29662436]
 [0.03904665 0.         0.14621366 ... 0.         1.         0.71397031]
 [0.         0.         0.         ... 0.29662436 0.71397031 1.        ]]
[[1.         0.56825577 0.06551191 ... 0.         0.03904665 0.        ]
 [0.56825577 1.         0.         ... 

matrix([[['6.588531055036267', '97673'],
         ['6.588531055036267', '103107'],
         ['6.735630599359265', '26366'],
         ['6.735630599359265', '49917'],
         ['6.931773294022449', '58191'],
         ['6.931773294022449', '60766'],
         ['6.931773294022449', '61357'],
         ['6.931773294022449', '137337'],
         ['6.951103967125734', '100365'],
         ['6.9918156683739925', '85394'],
         ['6.9918156683739925', '89260'],
         ['7.309680513300142', '3539'],
         ['7.309680513300142', '54881'],
         ['7.309680513300142', '107636'],
         ['7.309680513300142', '132458'],
         ['7.309680513300142', '164979'],
         ['7.613812487140812', '114254'],
         ['7.613812487140812', '161336'],
         ['8.559910271930667', '134859'],
         ['8.971372389540157', '117533']]], dtype='<U32')

In [221]:
sim_sum = np.sum(user_sim, axis=1)

In [371]:
np.ones((5,), dtype=int)*3

array([3, 3, 3, 3, 3])

In [362]:
a

matrix([[1.        , 0.56825577, 0.06551191],
        [0.56825577, 1.        , 0.        ],
        [0.06551191, 0.        , 1.        ],
        [0.0616256 , 0.        , 0.94067784]])

In [364]:
b

matrix([[1.69539328, 1.56825577, 2.00618975]])

In [238]:
ratings = pd.read_csv('./data/ratings.csv')
ratings = ratings[ratings['userId'] == 2]

user_rating = np.matrix(ratings['rating']).T
user_sim = get_partial_similarity(ratings['movieId'])
recommendation = np.divide(np.matmul(user_sim.T, user_rating), np.add(sim_sum, 1).T)

In [269]:
import locale
locale.getpreferredencoding()

'cp65001'

In [164]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
#np.concatenate((a, b), axis=0)
#np.concatenate((a, b), axis=1)
np.concatenate((a, b), axis=None)
#np.concatenate((a), axis=None)

array([1, 2, 3, 4])